---
- name: Create VM on oVirt-RHV
  hosts: all

  pre_tasks:
     - name: Login to oVirt-RHV
       ovirt_auth:
         hostname: "{{ rhvm }}"
         insecure: yes
         username: admin@internal
         password: "{{ passwordadmin }}"
     
  tasks:
    - name: Create VM from template 
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: "{{ clustername }}"
        template: "{{ templatename }}"
        name: "{{ fdqnvm }}"
        memory: "{{ memorynumber }}"
    
    - name: Logout from oVirt
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
