---
- name: Create VM on oVirt-RHV
  hosts: all

  pre_tasks:
     - name: Login to oVirt-RHV
       ovirt_auth:
         hostname: rhvm.csrh.local
         insecure: yes
         username: admin@internal
         password: "{{ password-admin }}"
     
  tasks:
    - name: Create VM from template 
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: "{{ cluster-name }}"
        template: "{{ template-name }}"
        name: "{{ fdqn-vm }}"
        memory: "{{ memory-number }}"

   
   post_tasks:
     - name: Logout from oVirt
       ovirt_auth:
         ovirt_auth: "{{ ovirt_auth }}"
         state: absent
